package com.example.desafioandroid

class Database {

    companion object {

        val imagemRestauranteUm = R.drawable.restaurant1
        val imagemRestauranteDois = R.drawable.restaurant2
        val imagemRestauranteTres = R.drawable.restaurant3
        val imagemRestauranteQuatro = R.drawable.restaurant4
        val imagemPratoOutback = R.drawable.costela
        val pratosRestaurantes = listOf(listOf(
            Prato("Salada com molho especial",
                imagemRestauranteDois,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Salada com molho especial",
                imagemRestauranteDois,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Salada com molho especial",
                imagemRestauranteDois,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Salada com molho especial",
                imagemRestauranteDois,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Salada com molho especial",
                imagemRestauranteDois,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Salada com molho especial",
                imagemRestauranteDois,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Salada com molho especial",
                imagemRestauranteDois,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Salada com molho especial",
                imagemRestauranteDois,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Salada com molho especial",
                imagemRestauranteDois,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Salada com molho especial",
                imagemRestauranteDois,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis.")
        ), listOf<Prato>(
            Prato("Especial da casa(camarão)",
                imagemRestauranteUm,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Especial da casa(camarão)",
                imagemRestauranteUm,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Especial da casa(camarão)",
                imagemRestauranteUm,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Especial da casa(camarão)",
                imagemRestauranteUm,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Especial da casa(camarão)",
                imagemRestauranteUm,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Especial da casa(camarão)",
                imagemRestauranteUm,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Especial da casa(camarão)",
                imagemRestauranteUm,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Especial da casa(camarão)",
                imagemRestauranteUm,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Especial da casa(camarão)",
                imagemRestauranteUm,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis."),
            Prato("Especial da casa(camarão)",
                imagemRestauranteUm,
                "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusant doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis.")
        ), listOf<Prato>(
            Prato("Costela",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela",
                imagemPratoOutback,
                "Costela no molho barbecue")
        ), listOf<Prato>(
            Prato("Costela1",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela1",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela1",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela1",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela1",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela1",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela1",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela1",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela1",
                imagemPratoOutback,
                "Costela no molho barbecue"),
            Prato("Costela1",
                imagemPratoOutback,
                "Costela no molho barbecue")
        )
        )


        val restaurant = listOf(
            Restaurante("Croasonho",
                "Av. Dr. Hugo Beolchi - Jabaquara",
                "22:00",
                imagemRestauranteUm,
                pratosRestaurantes[0]),
            Restaurante("Pei Hai",
                "Av. Jabaquara, 994 - Vila da Saúde",
                "00:00",
                imagemRestauranteDois,
                pratosRestaurantes[1]),
            Restaurante("Outback - Santa Cruz",
                "R. Domingos de Morais, 2564 - Vila Mariana",
                "22:00",
                imagemRestauranteTres,
                pratosRestaurantes[2]),
            Restaurante("Outback - Morumbi",
                "Av. Dr. Chucri Zaidan, 902, 902 - Vila Cordeiro",
                "22:00",
                imagemRestauranteTres,
                pratosRestaurantes[3])
        )
    }
}

